<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MusicSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //FIX YOU
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 1',
            'title' => 'Fix You',
            'genre' => 'Pop',
            'lyric' => 'When you try your ....., but you dont succeed',
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/AQl5nFnZPwk?si=CFEC5Px4H7XkKFDR',
            'artist' => 'Coldplay',
            'year_released' => '2005',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'fix_you.jpeg',
        ]);
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 1',
            'title' => 'Fix You',
            'genre' => 'Pop',
            'lyric' => 'When you love someone, but it goes to waste',
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/vxQtby0s7iI',
            'artist' => 'Coldplay',
            'year_released' => '2005',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'fix_you.jpeg',
        ]);
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 1',
            'title' => 'Fix You',
            'genre' => 'Pop',
            'lyric' => 'Lights will guide you home',
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/W891qcD-Da0?si=vlFo45GJPLwGZlAN',
            'artist' => 'Coldplay',
            'year_released' => '2005',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'fix_you.jpeg',
        ]);
        //LOVE STORY
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 1',
            'title' => 'Love Story',
            'genre' => 'Pop',
            'lyric' => 'We were both young when I first saw you',
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/ep1U4gtuZTU',
            'artist' => 'Taylor Swift',
            'year_released' => '2008',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'love_story.png',
        ]);
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 1',
            'title' => 'Love Story',
            'genre' => 'Pop',
            'lyric' => 'And I was cryin on the staircase. Beggin you, Please dont go',
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/43XEBGGHkmk?si=1uK5F0Qci3AFqyRG',
            'artist' => 'Taylor Swift',
            'year_released' => '2008',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'love_story.png',
        ]);
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 1',
            'title' => 'Love Story',
            'genre' => 'Pop',
            'lyric' => "Romeo, take me somewhere we can be alone I'll be waiting",
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/F3pKUxrk5A4?si=bLNvkQbUjQp57nd0',
            'artist' => 'Taylor Swift',
            'year_released' => '2008',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'love_story.png',
        ]);
        //VIVA LA VIDA
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 1',
            'title' => 'Viva La Vida',
            'genre' => 'Pop',
            'lyric' => 'I used to rule the world Seas would rise when I gave the word',
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/A429odNmeRM?si=Nioyjs5lF0XWP4Mz',
            'artist' => 'Coldplay',
            'year_released' => '2008',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'vivalavida.jpeg',
        ]);
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 1',
            'title' => 'Viva La Vida',
            'genre' => 'Pop',
            'lyric' => 'And I discovered that my castles stand Upon pillars of salt and pillars of sand',
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/nZ67CH3Wjfg?si=xqCwbQvcZY7sPGsQ',
            'artist' => 'Coldplay',
            'year_released' => '2008',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'vivalavida.jpeg',
        ]);
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 1',
            'title' => 'Viva La Vida',
            'genre' => 'Pop',
            'lyric' => 'I hear Jerusalem bells a-ringin Roman Cavalry choirs are singing',
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/ZgE14Y0b9Dg?si=WbxEpOBL0_qImuFy',
            'artist' => 'Coldplay',
            'year_released' => '2008',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'vivalavida.jpeg',
        ]);
        //REWRITE TEH STARS
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 1',
            'title' => 'Rewrite The Stars',
            'genre' => 'Pop',
            'lyric' => "You know I want you It's not a secret I try to hide",
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/4t8Ci5BA2Z8',
            'artist' => 'Anne-Marie & James Arthur',
            'year_released' => '2017',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'greatest_showman.jpeg',
        ]);
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 1',
            'title' => 'Rewrite The Stars',
            'genre' => 'Pop',
            'lyric' => "But you're hearing my heart So who can stop me if I decide it's on my destiny?",
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/Axph6S8RZs8',
            'artist' => 'Anne-Marie & James Arthur',
            'year_released' => '2017',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'greatest_showman.jpeg',
        ]);
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 1',
            'title' => 'Rewrite The Stars',
            'genre' => 'Pop',
            'lyric' => 'What if we rewrite the stars? Say you were made to be mine',
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/yrG9gfNnFgQ',
            'artist' => 'Anne-Marie & James Arthur',
            'year_released' => '2017',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'greatest_showman.jpeg',
        ]);
        //PREFECT
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 1',
            'title' => 'Perfect',
            'genre' => 'Pop',
            'lyric' => "When I first saw you From across the room",
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/SjkCzj1bUy8?si=eKkV_rzrwI1VIzWd',
            'artist' => 'One Direction',
            'year_released' => '2015',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'one_direction.jpeg',
        ]);
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 1',
            'title' => 'Perfect',
            'genre' => 'Pop',
            'lyric' => "And if you like having secret little rendezvous",
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/HlZXIRj13bs?si=m2GD8-4OYL_HDG0k',
            'artist' => 'One Direction',
            'year_released' => '2015',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'one_direction.jpeg',
        ]);
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 1',
            'title' => 'Perfect',
            'genre' => 'Pop',
            'lyric' => "If you like to do whatever you've been dreaming about",
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/fBP-YoLcc3w',
            'artist' => 'One Direction',
            'year_released' => '2015',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'one_direction.jpeg',
        ]);
        //CHAPTER 2
        //LALALA
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 2',
            'title' => 'Lalala',
            'genre' => 'Hip-Hop',
            'lyric' => 'When I popped off then your girl gave me just a little bit of lockjaw',
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/QCmiwiSVYXI?si=ZWiMpRGJz5Hc78kA',
            'artist' => 'Y2K, bbno$',
            'year_released' => '2019',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'lalala.png',
        ]);
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 2',
            'title' => 'Lalala',
            'genre' => 'Hip-Hop',
            'lyric' => 'Modest with my jewels but check the bank Finally got that money, say my thanks',
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/2b3EzAqv_vM?si=keXtiYYv6mim5e98',
            'artist' => 'Y2K, bbno$',
            'year_released' => '2019',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'lalala.png',
        ]);
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 2',
            'title' => 'Lalala',
            'genre' => 'Hip-Hop',
            'lyric' => 'Bankroll so low, I got nothing else that I can withdraw Ran out the door',
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/3NIWWXfJ33A?si=FZKt2A_hxIR5Eb1_',
            'artist' => 'Y2K, bbno$',
            'year_released' => '2019',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'lalala.png',
        ]);
        //HISTORY
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 2',
            'title' => 'History',
            'genre' => 'Hip-Hop',
            'lyric' => "We got history. Got me feeling the nostalgia. When you look at me",
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/kAQIMXMUUIU',
            'artist' => 'Rich Brian',
            'year_released' => '2018',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'history.jpg',
        ]);
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 2',
            'title' => 'History',
            'genre' => 'Hip-Hop',
            'lyric' => 'I know you said "gimme a hug", and I said "gimme a break"',
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/M0UbSzyjKW0',
            'artist' => 'Rich Brian',
            'year_released' => '2018',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'history.jpg',
        ]);
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 2',
            'title' => 'History',
            'genre' => 'Hip-Hop',
            'lyric' => "All these occasions. Let's work it out with me. I don't think it hurts to give another try on it",
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/3NIWWXfJ33A?si=FZKt2A_hxIR5Eb1_',
            'artist' => 'Rich Brian',
            'year_released' => '2018',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'history.jpg',
        ]);
        //Young Wild and Free
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 2',
            'title' => 'Young Wild and Free',
            'genre' => 'Hip-Hop',
            'lyric' => "So what we get drunk. So what we smoke weed",
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/kAQIMXMUUIU',
            'artist' => 'Wiz Khalifa & Snoop Dogg',
            'year_released' => '2021',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'wild.jpeg',
        ]);
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 2',
            'title' => 'Young Wild and Free',
            'genre' => 'Hip-Hop',
            'lyric' => "So what we go out. That's how it's supposed to be. Living young and wild and free",
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/M0UbSzyjKW0',
            'artist' => 'Wiz Khalifa & Snoop Dogg',
            'year_released' => '2021',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'wild.jpeg',
        ]);
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 2',
            'title' => 'Young Wild and Free',
            'genre' => 'Hip-Hop',
            'lyric' => "Uh, and I don't even care. 'Cause if me and my team in there. There's gon' be some weed in the air",
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/3NIWWXfJ33A?si=FZKt2A_hxIR5Eb1_',
            'artist' => 'Wiz Khalifa & Snoop Dogg',
            'year_released' => '2021',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'wild.jpeg',
        ]);
        //YOUNG DUMB & BROKE
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 2',
            'title' => 'Young Dumb & Broke',
            'genre' => 'Hip-Hop',
            'lyric' => "So you're still thinking of me. Just like I know you should",
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/kAQIMXMUUIU',
            'artist' => 'Khalid            ',
            'year_released' => '2017',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'young.jpeg',
        ]);
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 2',
            'title' => 'Young Dumb & Broke',
            'genre' => 'Hip-Hop',
            'lyric' => "Young dumb. Young, young dumb and broke",
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/M0UbSzyjKW0',
            'artist' => 'Khalid',
            'year_released' => '2017',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'young.jpeg',
        ]);
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 2',
            'title' => 'Young Dumb & Broke',
            'genre' => 'Hip-Hop',
            'lyric' => "Jump then we think, leave it all in the game of love Love",
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/3NIWWXfJ33A?si=FZKt2A_hxIR5Eb1_',
            'artist' => 'Khalid',
            'year_released' => '2017',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'young.jpeg',
        ]);
        //RAPGOD
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 2',
            'title' => 'Rap God',
            'genre' => 'Hip-Hop',
            'lyric' => "I'm beginnin' to feel like a Rap God, Rap God All my people from the front to the back nod, back nod",
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/kAQIMXMUUIU',
            'artist' => 'Eminem',
            'year_released' => '2013',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'rap_god.jpeg',
        ]);
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 2',
            'title' => 'Rap God',
            'genre' => 'Hip-Hop',
            'lyric' => 'Everybody loves to root for a nuisance. Hit the Earth like an asteroid. Did nothing but shoot for the Moon since',
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/M0UbSzyjKW0',
            'artist' => 'Eminem',
            'year_released' => '2013',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'rap_god.jpeg',
        ]);
        DB::table('music')->insert([
            'challenge_type' => 'Chapter 2',
            'title' => 'Rap God',
            'genre' => 'Hip-Hop',
            'lyric' => "'Cause I know the way to get 'em motivated. I make elevating music, you make elevator music",
            'option1' => 'best',
            'option2' => 'day',
            'option3' => 'west',
            'option4' => 'way',
            'option5' => 'self',
            'option6' => 'well',
            'answer_key' => 1,
            'youtube_link' => 'https://youtu.be/3NIWWXfJ33A?si=FZKt2A_hxIR5Eb1_',
            'artist' => 'Eminem',
            'year_released' => '2013',
            'guess_duration' => 30,
            'status' => false,
            'point' => 100,
            'image' => 'rap_god.jpeg',
        ]);
    }
}
